language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install black
script:
  - python3 Code/item_based.py 547
  - python3 Code/user_based.py 547
  - python3 test/item_testcases.py
  - python3 test/user_testcases.py
  - black --check Code/
  
after_success:
  - coveralls
